'use client'

import { FormEvent, useState } from 'react'
import { Eyebrow, Footer, Header } from '@/components/site-shell'

export default function RequestDemoPage() {
  const [sent, setSent] = useState(false)
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true) }
  return <main className="demo-page"><Header /><section className="demo-hero"><div className="site-shell demo-grid"><div className="demo-copy"><Eyebrow>REQUEST A DEMO / 01</Eyebrow><h1>See the system<br /><em>without the theatre.</em></h1><p>Bring your real questions. We&apos;ll show you how Saaf Trade connects research, risk, execution, and reporting — without ever asking you to move client funds.</p><div className="demo-proof"><span>◇</span><div><strong>30-minute working session</strong><small>For broker teams, wealth desks, and serious retail investors.</small></div></div></div><div className="demo-form-wrap">{sent ? <div className="success-state"><span className="success-icon">✓</span><Eyebrow>REQUEST RECEIVED</Eyebrow><h2>We&apos;ll be in touch.</h2><p>Thanks for reaching out. Our team will reply with a few times for a working session.</p></div> : <form className="demo-form" onSubmit={submit}><label>Name<input name="name" required placeholder="Your name" /></label><label>Work email<input name="email" type="email" required placeholder="you@company.com" /></label><label>I&apos;m exploring<select name="interest" defaultValue="broker"><option value="broker">Broker infrastructure</option><option value="investor">Investor tools</option><option value="partnership">A partnership</option></select></label><label>What should we know? <span className="optional">OPTIONAL</span><textarea name="message" rows={4} placeholder="Tell us a little about your setup" /></label><button className="button button-coral" type="submit">Request my demo <span>↗</span></button><small className="form-note">No sales sequence. No market promises. Just a useful conversation.</small></form>}</div></div></section><section className="demo-story"><div className="site-shell demo-story-grid"><img src="/saaf-human-editorial.png" alt="Trader reviewing a market system on a laptop" /><div><Eyebrow>COME CURIOUS</Eyebrow><h2>A better demo leaves you with <em>better questions.</em></h2><p>We&apos;ll walk through the signal path, show the risk controls in action, and make the boundaries clear. You&apos;ll see what Saaf Trade does — and what it deliberately does not.</p><div className="demo-bullets"><span>01 / Live trade-flow walkthrough</span><span>02 / Broker and investor use cases</span><span>03 / Honest answers on custody and risk</span></div></div></div></section><section className="demo-faq"><div className="site-shell"><Eyebrow>BEFORE WE MEET</Eyebrow><h2>Three things we&apos;ll never ask you to believe.</h2><div className="faq-grid"><div><b>01</b><strong>That returns are guaranteed.</strong><p>Markets are uncertain. Our job is to make the process disciplined, not magical.</p></div><div><b>02</b><strong>That you should move your money.</strong><p>Your capital remains with your own regulated broker.</p></div><div><b>03</b><strong>That a black box is good enough.</strong><p>Every important decision has a reason, a record, and an owner.</p></div></div></div></section><Footer /></main>
}
